[project]
name = "ditto-sionnart-bridge"
version = "0.1.0"
description = "A bridge for real-time radio propagation analysis using Eclipse Ditto and SionnaRT."
readme = "README.md"
requires-python = ">=3.10, <3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "sionna-rt==1.2.1",
    "tensorflow==2.19.0",
    "matplotlib==3.10.7",
    "numpy",
    "loguru",
    "PyYAML",
    "pydantic==2.12.4",
    "scene_generation",
    "rasterio",
    "requests",
    "shapely",
    "osmnx",
    "geopandas",
    "tqdm",
]

[project.optional-dependencies]
worldcover_ndvi = [
    "pystac-client",
    "planetary-computer",
]

[dependency-groups]
dev = ["ruff", "pytest"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.uv.sources]
scene_generation = { git = "https://github.com/functions-lab/geo2sigmap.git", subdirectory = "package" }
